---
dependency:
  name: galaxy
driver:
  name: docker
lint: flake8
platforms:
  - name: instance
    image: docker.io/pycontribs/debian:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
