---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    vpn_ip: 10.16.0.1/32
  - name: centos8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    vpn_ip: 10.16.0.2/32
  - name: debstable
    image: docker.io/pycontribs/debian:latest
    pre_build_image: true
    vpn_ip: 10.16.0.3/32
provisioner:
  name: ansible
verifier:
  name: ansible
